const vocabData = {
    "Year 7 (Themes)": {
        "Greetings & Numbers": [
            { char: "你好", jyutping: "nei5 hou2", meaning: "Hello" },
            { char: "我", jyutping: "ngo5", meaning: "I / Me" },
            { char: "叫", jyutping: "giu3", meaning: "Called (name)" },
            { char: "一", jyutping: "jat1", meaning: "One" },
            { char: "二", jyutping: "ji6", meaning: "Two" },
            { char: "三", jyutping: "saam1", meaning: "Three" },
            { char: "四", jyutping: "sei3", meaning: "Four" },
            { char: "五", jyutping: "ng5", meaning: "Five" },
            { char: "六", jyutping: "luk6", meaning: "Six" },
            { char: "七", jyutping: "cat1", meaning: "Seven" },
            { char: "八", jyutping: "baat3", meaning: "Eight" },
            { char: "九", jyutping: "gau2", meaning: "Nine" },
            { char: "十", jyutping: "sap6", meaning: "Ten" }
        ],
        "Family": [
            { char: "爸", jyutping: "baa4", meaning: "Dad" },
            { char: "媽", jyutping: "maa1", meaning: "Mom" },
            { char: "哥", jyutping: "go1", meaning: "Older Brother" },
            { char: "姐", jyutping: "ze2", meaning: "Older Sister" },
            { char: "弟", jyutping: "dai6", meaning: "Younger Brother" },
            { char: "妹", jyutping: "mui6", meaning: "Younger Sister" },
            { char: "人", jyutping: "jan4", meaning: "Person" }
        ]
    },
    "Year 8 (Themes)": {
        "Dates & Time": [
            { char: "年", jyutping: "nin4", meaning: "Year" },
            { char: "月", jyutping: "jyut6", meaning: "Month" },
            { char: "日", jyutping: "jat6", meaning: "Day" },
            { char: "生", jyutping: "saang1", meaning: "Birth" },
            { char: "幾", jyutping: "gei2", meaning: "How many / Which" },
            { char: "點", jyutping: "dim2", meaning: "O'clock" },
            { char: "分", jyutping: "fan1", meaning: "Minute" }
        ],
        "School": [
            { char: "學", jyutping: "hok6", meaning: "Study / Learn" },
            { char: "校", jyutping: "haau6", meaning: "School" },
            { char: "同學", jyutping: "tung4 hok6", meaning: "Classmate" },
            { char: "老師", jyutping: "lou5 si1", meaning: "Teacher" },
            { char: "中文", jyutping: "zung1 man4", meaning: "Chinese Language" }
        ]
    },
    "Year 9 (Themes)": {
        "Grammar & Modals": [
            { char: "想", jyutping: "soeng2", meaning: "Would like to / Think" },
            { char: "要", jyutping: "jiu3", meaning: "Want / Need / Will" },
            { char: "會", jyutping: "wui5", meaning: "Can (Learned) / Will" },
            { char: "能", jyutping: "nang4", meaning: "Can (Ability)" },
            { char: "可以", jyutping: "ho2 ji5", meaning: "Can / May" },
            { char: "應該", jyutping: "jing1 goi1", meaning: "Should" },
            { char: "必須", jyutping: "bit1 seoi1", meaning: "Must" },
            { char: "願意", jyutping: "jyun6 ji3", meaning: "Be willing to" },
            { char: "需要", jyutping: "seoi1 jiu3", meaning: "Need to" },
            { char: "敢", jyutping: "gam2", meaning: "Dare to" },
            { char: "得", jyutping: "dak1", meaning: "Must / Have to" }
        ],
        "Food & Drink": [
            { char: "吃", jyutping: "hek3", meaning: "Eat" },
            { char: "喝", jyutping: "hot3", meaning: "Drink" },
            { char: "飯", jyutping: "faan6", meaning: "Rice / Meal" },
            { char: "麵", jyutping: "min6", meaning: "Noodles" },
            { char: "水", jyutping: "seoi2", meaning: "Water" },
            { char: "茶", jyutping: "caa4", meaning: "Tea" }
        ],
        "Hobbies": [
            { char: "看", jyutping: "hon3", meaning: "Look / Watch" },
            { char: "書", jyutping: "syu1", meaning: "Book" },
            { char: "喜", jyutping: "hei2", meaning: "Like (1/2)" },
            { char: "歡", jyutping: "fun1", meaning: "Like (2/2)" },
            { char: "去", jyutping: "heoi3", meaning: "Go" },
            { char: "做", jyutping: "zou6", meaning: "Do" }
        ]
    },
    "VCE Vocabulary": {
        "A-G": [
            { char: "愛", jyutping: "oi3", meaning: "Love" }, { char: "安", jyutping: "on1", meaning: "Peace / Safe" },
            { char: "白", jyutping: "baak6", meaning: "White" }, { char: "班", jyutping: "baan1", meaning: "Class / Shift" },
            { char: "辦", jyutping: "baan6", meaning: "Do / Manage" },
            { char: "半", jyutping: "bun3", meaning: "Half" }, { char: "包", jyutping: "baau1", meaning: "Bag / Wrap" },
            { char: "飽", jyutping: "baau2", meaning: "Full (eaten)" }, { char: "報", jyutping: "bou3", meaning: "Newspaper / Report" },
            { char: "杯", jyutping: "bui1", meaning: "Cup" }, { char: "本", jyutping: "bun2", meaning: "Measure word for books / Root" },
            { char: "比", jyutping: "bei2", meaning: "Compare" }, { char: "筆", jyutping: "bat1", meaning: "Pen" },
            { char: "邊", jyutping: "bin1", meaning: "Side" }, { char: "變", jyutping: "bin3", meaning: "Change" },
            { char: "便", jyutping: "bin6", meaning: "Convenient" }, { char: "表", jyutping: "biu2", meaning: "Watch / Surface / Form" },
            { char: "別", jyutping: "bit6", meaning: "Don't / Other" }, { char: "病", jyutping: "beng6", meaning: "Sick" },
            { char: "不", jyutping: "bat1", meaning: "No / Not" }, { char: "部", jyutping: "bou6", meaning: "Part / Department" },
            { char: "菜", jyutping: "coi3", meaning: "Dish / Vegetable" }, { char: "參", jyutping: "caam1", meaning: "Participate" },
            { char: "茶", jyutping: "caa4", meaning: "Tea" }, { char: "差", jyutping: "caa1", meaning: "Difference / Bad" },
            { char: "長", jyutping: "coeng4", meaning: "Long" }, { char: "常", jyutping: "soeng4", meaning: "Often" },
            { char: "場", jyutping: "coeng4", meaning: "Field / Place" }, { char: "唱", jyutping: "coeng3", meaning: "Sing" },
            { char: "吵", jyutping: "caau2", meaning: "Noisy / Argue" }, { char: "車", jyutping: "ce1", meaning: "Car" },
            { char: "成", jyutping: "sing4", meaning: "Become / Success" }, { char: "城", jyutping: "sing4", meaning: "City" },
            { char: "吃", jyutping: "hek3", meaning: "Eat" }, { char: "出", jyutping: "ceot1", meaning: "Out" },
            { char: "處", jyutping: "cyu3", meaning: "Place" }, { char: "穿", jyutping: "cyun1", meaning: "Wear" },
            { char: "床", jyutping: "cong4", meaning: "Bed" }, { char: "春", jyutping: "ceon1", meaning: "Spring" },
            { char: "次", jyutping: "ci3", meaning: "Time (occurrence)" }, { char: "從", jyutping: "cung4", meaning: "From" },
            { char: "錯", jyutping: "co3", meaning: "Wrong" }, { char: "打", jyutping: "daa2", meaning: "Hit / Play" },
            { char: "大", jyutping: "daai6", meaning: "Big" }, { char: "帶", jyutping: "daai3", meaning: "Bring / Belt" },
            { char: "但", jyutping: "daan6", meaning: "But" }, { char: "蛋", jyutping: "daan2", meaning: "Egg" },
            { char: "當", jyutping: "dong1", meaning: "When / Serve as" }, { char: "到", jyutping: "dou3", meaning: "Arrive" },
            { char: "的", jyutping: "dik1", meaning: "Possessive particle" }, { char: "得", jyutping: "dak1", meaning: "Get / Particle" },
            { char: "地", jyutping: "dei6", meaning: "Ground / Particle" }, { char: "等", jyutping: "dang2", meaning: "Wait" },
            { char: "點", jyutping: "dim2", meaning: "Dot / O'clock" }, { char: "電", jyutping: "din6", meaning: "Electricity" },
            { char: "店", jyutping: "dim3", meaning: "Shop" }, { char: "訂", jyutping: "deng6", meaning: "Order / Book" },
            { char: "丟", jyutping: "diu1", meaning: "Lose" }, { char: "東", jyutping: "dung1", meaning: "East" },
            { char: "冬", jyutping: "dung1", meaning: "Winter" }, { char: "動", jyutping: "dung6", meaning: "Move" },
            { char: "都", jyutping: "dou1", meaning: "All" }, { char: "度", jyutping: "dou6", meaning: "Degree" },
            { char: "短", jyutping: "dyun2", meaning: "Short" }, { char: "對", jyutping: "deoi3", meaning: "Correct / Facing" },
            { char: "隊", jyutping: "deoi6", meaning: "Team" }, { char: "多", jyutping: "do1", meaning: "Many" },
            { char: "餓", jyutping: "ngo6", meaning: "Hungry" }, { char: "兒", jyutping: "ji4", meaning: "Son / Child" },
            { char: "發", jyutping: "faat3", meaning: "Send / Emit" }, { char: "法", jyutping: "faat3", meaning: "Method / Law" },
            { char: "飯", jyutping: "faan6", meaning: "Rice / Meal" }, { char: "方", jyutping: "fong1", meaning: "Square / Direction" },
            { char: "房", jyutping: "fong2", meaning: "Room / House" }, { char: "訪", jyutping: "fong2", meaning: "Visit" },
            { char: "放", jyutping: "fong3", meaning: "Put / Release" }, { char: "飛", jyutping: "fei1", meaning: "Fly" },
            { char: "非", jyutping: "fei1", meaning: "Not / Wrong" }, { char: "費", jyutping: "fai3", meaning: "Fee / Cost" },
            { char: "分", jyutping: "fan1", meaning: "Minute / Divide" }, { char: "風", jyutping: "fung1", meaning: "Wind" },
            { char: "豐", jyutping: "fung1", meaning: "Abundant" }, { char: "服", jyutping: "fuk6", meaning: "Clothes / Convinced" },
            { char: "福", jyutping: "fuk1", meaning: "Fortune" }, { char: "富", jyutping: "fu3", meaning: "Rich" },
            { char: "該", jyutping: "goi1", meaning: "Should / Ought to" }, { char: "改", jyutping: "goi2", meaning: "Change" },
            { char: "感", jyutping: "gam2", meaning: "Feel" }, { char: "剛", jyutping: "gong1", meaning: "Just now" },
            { char: "高", jyutping: "gou1", meaning: "High / Tall" }, { char: "告", jyutping: "gou3", meaning: "Tell" },
            { char: "歌", jyutping: "go1", meaning: "Song" }, { char: "個", jyutping: "go3", meaning: "Individual / Measure word" },
            { char: "給", jyutping: "kap1", meaning: "Give" }, { char: "更", jyutping: "gang3", meaning: "Even more" },
            { char: "工", jyutping: "gung1", meaning: "Work" }, { char: "公", jyutping: "gung1", meaning: "Public" },
            { char: "功", jyutping: "gung1", meaning: "Merit / Gong" }, { char: "共", jyutping: "gung6", meaning: "Together" },
            { char: "古", jyutping: "gu2", meaning: "Ancient" }, { char: "故", jyutping: "gu3", meaning: "Old / Cause" },
            { char: "官", jyutping: "gun1", meaning: "Official" }, { char: "狗", jyutping: "gau2", meaning: "Dog" },
            { char: "關", jyutping: "gwaan1", meaning: "Close / Pass" }, { char: "觀", jyutping: "gun1", meaning: "View / Observe" },
            { char: "館", jyutping: "gun2", meaning: "Shop / Establishment" }, { char: "規", jyutping: "kwai1", meaning: "Rule" },
            { char: "貴", jyutping: "gwai3", meaning: "Expensive / Noble" }, { char: "國", jyutping: "gwok3", meaning: "Country" },
            { char: "果", jyutping: "gwo2", meaning: "Fruit / Result" }, { char: "過", jyutping: "gwo3", meaning: "Pass / Cross" }
        ],
        "H-N": [
            { char: "還", jyutping: "waan4", meaning: "Also / Return" }, { char: "海", jyutping: "hoi2", meaning: "Sea" },
            { char: "孩", jyutping: "haai4", meaning: "Child" }, { char: "漢", jyutping: "hon3", meaning: "Chinese / Han" },
            { char: "行", jyutping: "hang4", meaning: "Walk / OK" }, { char: "好", jyutping: "hou2", meaning: "Good" },
            { char: "號", jyutping: "hou6", meaning: "Number / Date" }, { char: "喝", jyutping: "hot3", meaning: "Drink" },
            { char: "和", jyutping: "wo4", meaning: "And / Harmony" }, { char: "河", jyutping: "ho4", meaning: "River" },
            { char: "合", jyutping: "hap6", meaning: "Combine / Close" }, { char: "黑", jyutping: "hak1", meaning: "Black" },
            { char: "很", jyutping: "han2", meaning: "Very" }, { char: "紅", jyutping: "hung4", meaning: "Red" },
            { char: "候", jyutping: "hau6", meaning: "Wait / Time" }, { char: "後", jyutping: "hau6", meaning: "Behind / After" },
            { char: "花", jyutping: "faa1", meaning: "Flower / Spend" }, { char: "華", jyutping: "waa4", meaning: "China / Magnificent" },
            { char: "話", jyutping: "waa6", meaning: "Word / Talk" }, { char: "化", jyutping: "faa3", meaning: "Change / Melt" },
            { char: "划", jyutping: "waa4", meaning: "Row / Scratch" }, { char: "畫", jyutping: "waa2", meaning: "Draw / Picture" },
            { char: "壞", jyutping: "waai6", meaning: "Bad / Broken" }, { char: "歡", jyutping: "fun1", meaning: "Happy" },
            { char: "換", jyutping: "wun6", meaning: "Change / Exchange" }, { char: "黃", jyutping: "wong4", meaning: "Yellow" },
            { char: "回", jyutping: "wui4", meaning: "Return" }, { char: "會", jyutping: "wui5", meaning: "Meeting / Can" },
            { char: "活", jyutping: "wut6", meaning: "Live / Alive" }, { char: "或", jyutping: "waak6", meaning: "Or" },
            { char: "機", jyutping: "gei1", meaning: "Machine / Chance" }, { char: "級", jyutping: "kap1", meaning: "Level / Grade" },
            { char: "幾", jyutping: "gei2", meaning: "How many / A few" }, { char: "己", jyutping: "gei2", meaning: "Self" },
            { char: "計", jyutping: "gai3", meaning: "Count / Plan" }, { char: "記", jyutping: "gei3", meaning: "Remember / Record" },
            { char: "技", jyutping: "gei6", meaning: "Skill" }, { char: "季", jyutping: "gwai3", meaning: "Season" },
            { char: "家", jyutping: "gaa1", meaning: "Family / Home" }, { char: "假", jyutping: "gaa2", meaning: "Fake / Holiday" },
            { char: "間", jyutping: "gaan1", meaning: "Between / Room" }, { char: "件", jyutping: "gin6", meaning: "Piece (measure word)" },
            { char: "見", jyutping: "gin3", meaning: "See" }, { char: "建", jyutping: "gin3", meaning: "Build" },
            { char: "將", jyutping: "zoeng1", meaning: "Will / Shall" }, { char: "交", jyutping: "gaau1", meaning: "Hand over / Interact" },
            { char: "教", jyutping: "gaau3", meaning: "Teach" }, { char: "餃", jyutping: "gaau2", meaning: "Dumpling" },
            { char: "叫", jyutping: "giu3", meaning: "Call" }, { char: "較", jyutping: "gaau3", meaning: "Compare / Relatively" },
            { char: "覺", jyutping: "gok3", meaning: "Feel / Sleep" }, { char: "街", jyutping: "gaai1", meaning: "Street" },
            { char: "接", jyutping: "zip3", meaning: "Receive / Pick up" }, { char: "節", jyutping: "zit3", meaning: "Festival / Section" },
            { char: "借", jyutping: "ze3", meaning: "Borrow / Lend" }, { char: "今", jyutping: "gam1", meaning: "Today / Now" },
            { char: "緊", jyutping: "gan2", meaning: "Tight" }, { char: "進", jyutping: "zeon3", meaning: "Enter" },
            { char: "近", jyutping: "kan5", meaning: "Near" }, { char: "京", jyutping: "ging1", meaning: "Capital" },
            { char: "經", jyutping: "ging1", meaning: "Pass through / Classic" }, { char: "景", jyutping: "ging2", meaning: "Scenery" },
            { char: "久", jyutping: "gau2", meaning: "Long time" }, { char: "酒", jyutping: "zau2", meaning: "Wine / Alcohol" },
            { char: "舊", jyutping: "gau6", meaning: "Old (objects)" }, { char: "就", jyutping: "zau6", meaning: "Then / Just" },
            { char: "劇", jyutping: "kek6", meaning: "Drama / Play" }, { char: "開", jyutping: "hoi1", meaning: "Open / Start" },
            { char: "看", jyutping: "hon3", meaning: "Look / Read" }, { char: "考", jyutping: "haau2", meaning: "Test / Exam" },
            { char: "科", jyutping: "fo1", meaning: "Subject / Science" }, { char: "可", jyutping: "ho2", meaning: "Can" },
            { char: "客", jyutping: "haak3", meaning: "Guest" }, { char: "課", jyutping: "fo3", meaning: "Class / Lesson" },
            { char: "刻", jyutping: "hak1", meaning: "Carve / Quarter hour" }, { char: "空", jyutping: "hung1", meaning: "Empty / Air" },
            { char: "口", jyutping: "hau2", meaning: "Mouth" }, { char: "塊", jyutping: "faai3", meaning: "Piece / Dollar" },
            { char: "快", jyutping: "faai3", meaning: "Fast" }, { char: "來", jyutping: "loi4", meaning: "Come" },
            { char: "藍", jyutping: "laam4", meaning: "Blue" }, { char: "籃", jyutping: "laam4", meaning: "Basket" },
            { char: "老", jyutping: "lou5", meaning: "Old" }, { char: "了", jyutping: "liu5", meaning: "Particle / Finish" },
            { char: "樂", jyutping: "lok6", meaning: "Happy / Music" }, { char: "累", jyutping: "leoi6", meaning: "Tired" },
            { char: "冷", jyutping: "laang5", meaning: "Cold" }, { char: "離", jyutping: "lei4", meaning: "Leave / From" },
            { char: "裡", jyutping: "lei5", meaning: "Inside / Mile" }, { char: "理", jyutping: "lei5", meaning: "Reason / Manage" },
            { char: "力", jyutping: "lik6", meaning: "Power" }, { char: "利", jyutping: "lei6", meaning: "Benefit / Sharp" },
            { char: "歷", jyutping: "lik6", meaning: "History / Experience" }, { char: "練", jyutping: "lin6", meaning: "Practice" },
            { char: "兩", jyutping: "loeng5", meaning: "Two" }, { char: "另", jyutping: "ling6", meaning: "Other" },
            { char: "龍", jyutping: "lung4", meaning: "Dragon" }, { char: "樓", jyutping: "lau4", meaning: "Building / Floor" },
            { char: "路", jyutping: "lou6", meaning: "Road" }, { char: "亂", jyutping: "lyun6", meaning: "Messy / Chaotic" },
            { char: "旅", jyutping: "leoi5", meaning: "Travel" }, { char: "綠", jyutping: "luk6", meaning: "Green" },
            { char: "馬", jyutping: "maa5", meaning: "Horse" }, { char: "嗎", jyutping: "maa3", meaning: "Question particle" },
            { char: "買", jyutping: "maai5", meaning: "Buy" }, { char: "賣", jyutping: "maai6", meaning: "Sell" },
            { char: "慢", jyutping: "maan6", meaning: "Slow" }, { char: "忙", jyutping: "mong4", meaning: "Busy" },
            { char: "貓", jyutping: "maau1", meaning: "Cat" }, { char: "麼", jyutping: "mo1", meaning: "What (suffix)" },
            { char: "沒", jyutping: "mut6", meaning: "No / Not have" }, { char: "美", jyutping: "mei5", meaning: "Beautiful" },
            { char: "每", jyutping: "mui5", meaning: "Every" }, { char: "門", jyutping: "mun4", meaning: "Door" },
            { char: "們", jyutping: "mun4", meaning: "Plural suffix" }, { char: "迷", jyutping: "mai4", meaning: "Fan / Lost" },
            { char: "米", jyutping: "mai5", meaning: "Rice / Meter" }, { char: "麵", jyutping: "min6", meaning: "Noodles" },
            { char: "明", jyutping: "ming4", meaning: "Bright / Tomorrow" }, { char: "名", jyutping: "ming4", meaning: "Name" },
            { char: "末", jyutping: "mut6", meaning: "End" }, { char: "哪", jyutping: "naa5", meaning: "Which / Where" },
            { char: "那", jyutping: "naa5", meaning: "That" }, { char: "男", jyutping: "naam4", meaning: "Male" },
            { char: "南", jyutping: "naam4", meaning: "South" }, { char: "難", jyutping: "naan4", meaning: "Difficult" },
            { char: "腦", jyutping: "nou5", meaning: "Brain" }, { char: "鬧", jyutping: "naau6", meaning: "Noisy" },
            { char: "呢", jyutping: "ne1", meaning: "Particle" }, { char: "能", jyutping: "nang4", meaning: "Can" },
            { char: "你", jyutping: "nei5", meaning: "You" }, { char: "年", jyutping: "nin4", meaning: "Year" },
            { char: "您", jyutping: "nei5", meaning: "You (Polite)" }, { char: "牛", jyutping: "ngau4", meaning: "Cow" },
            { char: "努", jyutping: "nou5", meaning: "Strive" }, { char: "女", jyutping: "neoi5", meaning: "Female" }
        ],
        "P-T": [
            { char: "怕", jyutping: "paa3", meaning: "Fear" }, { char: "跑", jyutping: "paau2", meaning: "Run" },
            { char: "胖", jyutping: "pun6", meaning: "Fat" }, { char: "朋", jyutping: "pang4", meaning: "Friend" },
            { char: "片", jyutping: "pin3", meaning: "Slice / Film" }, { char: "漂", jyutping: "piu1", meaning: "Float / Bleach" },
            { char: "票", jyutping: "piu3", meaning: "Ticket" }, { char: "平", jyutping: "ping4", meaning: "Flat / Peace" },
            { char: "期", jyutping: "kei4", meaning: "Period" }, { char: "騎", jyutping: "ke4", meaning: "Ride" },
            { char: "起", jyutping: "hei2", meaning: "Up / Start" }, { char: "氣", jyutping: "hei3", meaning: "Air / Gas" },
            { char: "汽", jyutping: "hei3", meaning: "Steam / Car" }, { char: "前", jyutping: "cin4", meaning: "Front / Before" },
            { char: "錢", jyutping: "cin2", meaning: "Money" }, { char: "親", jyutping: "can1", meaning: "Parent / Dear" },
            { char: "輕", jyutping: "hing1", meaning: "Light (weight)" }, { char: "情", jyutping: "cing4", meaning: "Feeling / Situation" },
            { char: "晴", jyutping: "cing4", meaning: "Sunny" }, { char: "慶", jyutping: "hing3", meaning: "Celebrate" },
            { char: "請", jyutping: "cing2", meaning: "Please / Invite" }, { char: "秋", jyutping: "cau1", meaning: "Autumn" },
            { char: "球", jyutping: "kau4", meaning: "Ball" }, { char: "去", jyutping: "heoi3", meaning: "Go" },
            { char: "趣", jyutping: "ceoi3", meaning: "Interest" }, { char: "然", jyutping: "jin4", meaning: "Correct / So" },
            { char: "讓", jyutping: "joeng6", meaning: "Let / Allow" }, { char: "熱", jyutping: "jit6", meaning: "Hot" },
            { char: "人", jyutping: "jan4", meaning: "Person" }, { char: "認", jyutping: "jing6", meaning: "Recognize" },
            { char: "日", jyutping: "jat6", meaning: "Sun / Day" }, { char: "容", jyutping: "jung4", meaning: "Contain / Face" },
            { char: "肉", jyutping: "juk6", meaning: "Meat" }, { char: "如", jyutping: "jyu4", meaning: "As / If" },
            { char: "賽", jyutping: "coi3", meaning: "Competition" }, { char: "色", jyutping: "sik1", meaning: "Color" },
            { char: "山", jyutping: "saan1", meaning: "Mountain" }, { char: "商", jyutping: "soeng1", meaning: "Business" },
            { char: "上", jyutping: "soeng6", meaning: "Up" }, { char: "少", jyutping: "siu2", meaning: "Few" },
            { char: "誰", jyutping: "seoi4", meaning: "Who" }, { char: "社", jyutping: "se5", meaning: "Society" },
            { char: "身", jyutping: "san1", meaning: "Body" }, { char: "甚", jyutping: "sam6", meaning: "What" },
            { char: "生", jyutping: "saang1", meaning: "Life / Birth" }, { char: "師", jyutping: "si1", meaning: "Teacher / Master" },
            { char: "詩", jyutping: "si1", meaning: "Poem" }, { char: "時", jyutping: "si4", meaning: "Time" },
            { char: "識", jyutping: "sik1", meaning: "Know" }, { char: "史", jyutping: "si2", meaning: "History" },
            { char: "始", jyutping: "ci2", meaning: "Start" }, { char: "市", jyutping: "si5", meaning: "Market / City" },
            { char: "是", jyutping: "si6", meaning: "Is / Am / Are" }, { char: "試", jyutping: "si3", meaning: "Try / Test" },
            { char: "視", jyutping: "si6", meaning: "View" }, { char: "事", jyutping: "si6", meaning: "Matter" },
            { char: "室", jyutping: "sat1", meaning: "Room" }, { char: "收", jyutping: "sau1", meaning: "Collect / Receive" },
            { char: "手", jyutping: "sau2", meaning: "Hand" }, { char: "受", jyutping: "sau6", meaning: "Receive / Bear" },
            { char: "瘦", jyutping: "sau3", meaning: "Thin" }, { char: "書", jyutping: "syu1", meaning: "Book" },
            { char: "舒", jyutping: "syu1", meaning: "Comfortable" }, { char: "數", jyutping: "sou2", meaning: "Count / Number" },
            { char: "水", jyutping: "seoi2", meaning: "Water" }, { char: "睡", jyutping: "seoi6", meaning: "Sleep" },
            { char: "說", jyutping: "syut3", meaning: "Speak" }, { char: "思", jyutping: "si1", meaning: "Think" },
            { char: "送", jyutping: "sung3", meaning: "Send / Gift" }, { char: "訴", jyutping: "sou3", meaning: "Tell / Complain" },
            { char: "歲", jyutping: "seoi3", meaning: "Years old" }, { char: "所", jyutping: "so2", meaning: "Place" },
            { char: "太", jyutping: "taai3", meaning: "Too / Very" }, { char: "談", jyutping: "taam4", meaning: "Chat" },
            { char: "湯", jyutping: "tong1", meaning: "Soup" }, { char: "堂", jyutping: "tong4", meaning: "Hall / Class" },
            { char: "題", jyutping: "tai4", meaning: "Topic / Question" }, { char: "體", jyutping: "tai2", meaning: "Body" },
            { char: "天", jyutping: "tin1", meaning: "Sky / Day" }, { char: "條", jyutping: "tiu4", meaning: "Strip (measure word)" },
            { char: "聽", jyutping: "teng1", meaning: "Listen" }, { char: "停", jyutping: "ting4", meaning: "Stop" },
            { char: "挺", jyutping: "ting5", meaning: "Very / Straight" }, { char: "同", jyutping: "tung4", meaning: "Same" },
            { char: "頭", jyutping: "tau4", meaning: "Head" }, { char: "圖", jyutping: "tou4", meaning: "Picture" }
        ],
        "W-Z": [
            { char: "外", jyutping: "ngoi6", meaning: "Outside" }, { char: "玩", jyutping: "waan2", meaning: "Play" },
            { char: "完", jyutping: "jyun4", meaning: "Finish" }, { char: "晚", jyutping: "maan5", meaning: "Late / Evening" },
            { char: "網", jyutping: "mong5", meaning: "Net / Web" }, { char: "忘", jyutping: "mong4", meaning: "Forget" },
            { char: "望", jyutping: "mong6", meaning: "Hope / Gaze" }, { char: "為", jyutping: "wai4", meaning: "For / Be" },
            { char: "位", jyutping: "wai2", meaning: "Seat / Rank" }, { char: "味", jyutping: "mei6", meaning: "Taste" },
            { char: "文", jyutping: "man4", meaning: "Culture / Text" }, { char: "問", jyutping: "man6", meaning: "Ask" },
            { char: "我", jyutping: "ngo5", meaning: "I / Me" }, { char: "午", jyutping: "ng5", meaning: "Noon" },
            { char: "物", jyutping: "mat6", meaning: "Thing" }, { char: "西", jyutping: "sai1", meaning: "West" },
            { char: "息", jyutping: "sik1", meaning: "Breath / Rest" }, { char: "習", jyutping: "zaap6", meaning: "Practice" },
            { char: "洗", jyutping: "sai2", meaning: "Wash" }, { char: "喜", jyutping: "hei2", meaning: "Like / Happy" },
            { char: "下", jyutping: "haa6", meaning: "Down" }, { char: "夏", jyutping: "haa6", meaning: "Summer" },
            { char: "先", jyutping: "sin1", meaning: "First" }, { char: "鮮", jyutping: "sin1", meaning: "Fresh" },
            { char: "現", jyutping: "jin6", meaning: "Present / Now" }, { char: "相", jyutping: "soeng1", meaning: "Mutual / Picture" },
            { char: "想", jyutping: "soeng2", meaning: "Think / Want" }, { char: "象", jyutping: "zoeng6", meaning: "Elephant / Image" },
            { char: "小", jyutping: "siu2", meaning: "Small" }, { char: "笑", jyutping: "siu3", meaning: "Laugh" },
            { char: "校", jyutping: "haau6", meaning: "School" }, { char: "些", jyutping: "se1", meaning: "Some" },
            { char: "寫", jyutping: "se2", meaning: "Write" }, { char: "謝", jyutping: "ze6", meaning: "Thank" },
            { char: "心", jyutping: "sam1", meaning: "Heart" }, { char: "新", jyutping: "san1", meaning: "New" },
            { char: "信", jyutping: "seon3", meaning: "Letter / Believe" }, { char: "星", jyutping: "sing1", meaning: "Star" },
            { char: "興", jyutping: "hing1", meaning: "Excitement" }, { char: "姓", jyutping: "sing3", meaning: "Surname" },
            { char: "休", jyutping: "jau1", meaning: "Rest" }, { char: "學", jyutping: "hok6", meaning: "Study" },
            { char: "亞", jyutping: "aa3", meaning: "Asia" }, { char: "顏", jyutping: "ngaan4", meaning: "Color / Face" },
            { char: "羊", jyutping: "joeng4", meaning: "Sheep" }, { char: "養", jyutping: "joeng5", meaning: "Raise" },
            { char: "樣", jyutping: "joeng6", meaning: "Appearance" }, { char: "要", jyutping: "jiu3", meaning: "Want" },
            { char: "藥", jyutping: "joek6", meaning: "Medicine" }, { char: "也", jyutping: "jaa5", meaning: "Also" },
            { char: "業", jyutping: "jip6", meaning: "Business / Karma" }, { char: "衣", jyutping: "ji1", meaning: "Clothes" },
            { char: "醫", jyutping: "ji1", meaning: "Doctor / Medicine" }, { char: "宜", jyutping: "ji4", meaning: "Suitable" },
            { char: "已", jyutping: "ji5", meaning: "Already" }, { char: "以", jyutping: "ji5", meaning: "By / With" },
            { char: "易", jyutping: "jik6", meaning: "Easy" }, { char: "意", jyutping: "ji3", meaning: "Meaning" },
            { char: "音", jyutping: "jam1", meaning: "Sound" }, { char: "應", jyutping: "jing1", meaning: "Should" },
            { char: "英", jyutping: "jing1", meaning: "Hero / English" }, { char: "迎", jyutping: "jing4", meaning: "Welcome" },
            { char: "影", jyutping: "jing2", meaning: "Shadow / Film" }, { char: "泳", jyutping: "wing6", meaning: "Swim" },
            { char: "用", jyutping: "jung6", meaning: "Use" }, { char: "游", jyutping: "jau4", meaning: "Swim / Tour" },
            { char: "友", jyutping: "jau5", meaning: "Friend" }, { char: "有", jyutping: "jau5", meaning: "Have" },
            { char: "右", jyutping: "jau6", meaning: "Right" }, { char: "魚", jyutping: "jyu4", meaning: "Fish" },
            { char: "雨", jyutping: "jyu5", meaning: "Rain" }, { char: "語", jyutping: "jyu5", meaning: "Language" },
            { char: "元", jyutping: "jyun4", meaning: "Yuan / Dollar" }, { char: "園", jyutping: "jyun4", meaning: "Garden" },
            { char: "遠", jyutping: "jyun5", meaning: "Far" }, { char: "院", jyutping: "jyun2", meaning: "Institution / Courtyard" },
            { char: "月", jyutping: "jyut6", meaning: "Moon / Month" }, { char: "運", jyutping: "wan6", meaning: "Luck / Transport" },
            { char: "在", jyutping: "zoi6", meaning: "at" }, { char: "再", jyutping: "zoi3", meaning: "Again" },
            { char: "早", jyutping: "zou2", meaning: "Early" }, { char: "怎", jyutping: "zam2", meaning: "How" },
            { char: "站", jyutping: "zaam6", meaning: "Station / Stand" }, { char: "找", jyutping: "zaau2", meaning: "Find" },
            { char: "者", jyutping: "ze2", meaning: "One who" }, { char: "這", jyutping: "ze2", meaning: "This" },
            { char: "真", jyutping: "zan1", meaning: "Real" }, { char: "正", jyutping: "zing3", meaning: "Correct" },
            { char: "衹", jyutping: "zi2", meaning: "Only" }, { char: "知", jyutping: "zi1", meaning: "Know" },
            { char: "中", jyutping: "zung1", meaning: "Middle" }, { char: "種", jyutping: "zung2", meaning: "Kind / Seed" },
            { char: "重", jyutping: "cung5", meaning: "Heavy" }, { char: "住", jyutping: "zyu6", meaning: "Live" },
            { char: "祝", jyutping: "zuk1", meaning: "Wish" }, { char: "子", jyutping: "zi2", meaning: "Son / Child" },
            { char: "自", jyutping: "zi6", meaning: "Self" }, { char: "字", jyutping: "zi6", meaning: "Character" },
            { char: "總", jyutping: "zung2", meaning: "Total / Always" }, { char: "走", jyutping: "zau2", meaning: "Walk" },
            { char: "最", jyutping: "zeoi3", meaning: "Most" }, { char: "昨", jyutping: "zok6", meaning: "Yesterday" },
            { char: "左", jyutping: "zo2", meaning: "Left" }, { char: "作", jyutping: "zok3", meaning: "Work" },
            { char: "坐", jyutping: "co5", meaning: "Sit" }, { char: "做", jyutping: "zou6", meaning: "Do" }
        ]
    },
    "Special Terms": {
        "Numbers": [
            { char: "零", jyutping: "ling4", meaning: "Zero" }, { char: "百", jyutping: "baak3", meaning: "Hundred" },
            { char: "千", jyutping: "cin1", meaning: "Thousand" }, { char: "萬", jyutping: "maan6", meaning: "Ten Thousand" },
            { char: "億", jyutping: "jik1", meaning: "Hundred Million" }
        ],
        "Family": [
            { char: "爺爺", jyutping: "je4 je4", meaning: "Grandpa (Paternal)" }, { char: "奶奶", jyutping: "naai5 naai5", meaning: "Grandma (Paternal)" },
            { char: "姥爺", jyutping: "lou5 je4", meaning: "Grandpa (Maternal - Northern)" }, { char: "姥姥", jyutping: "lou5 lou5", meaning: "Grandma (Maternal - Northern)" },
            { char: "外公", jyutping: "ngoi6 gung1", meaning: "Grandpa (Maternal)" }, { char: "外婆", jyutping: "ngoi6 po4", meaning: "Grandma (Maternal)" },
            { char: "爸爸", jyutping: "baa4 baa1", meaning: "Dad" }, { char: "媽媽", jyutping: "maa1 maa1", meaning: "Mom" },
            { char: "伯父", jyutping: "baak3 fu6", meaning: "Uncle (Older)" }, { char: "伯母", jyutping: "baak3 mou5", meaning: "Aunt (Older)" },
            { char: "哥哥", jyutping: "go1 go1", meaning: "Older Brother" }, { char: "姐姐", jyutping: "ze2 ze2", meaning: "Older Sister" },
            { char: "弟弟", jyutping: "dai6 dai6", meaning: "Younger Brother" }, { char: "妹妹", jyutping: "mui6 mui6", meaning: "Younger Sister" },
            { char: "姑姑", jyutping: "gu1 gu1", meaning: "Aunt (Paternal)" }, { char: "叔叔", jyutping: "suk1 suk1", meaning: "Uncle (Younger)" },
            { char: "阿姨", jyutping: "aa3 ji4", meaning: "Aunt (Maternal)" }
        ],
        "Locations": [
            { char: "澳大利亞", jyutping: "ou3 daai6 lei6 aa3", meaning: "Australia" }, { char: "墨爾本", jyutping: "mak6 ji5 bun2", meaning: "Melbourne" },
            { char: "悉尼", jyutping: "sik1 nei4", meaning: "Sydney" }, { char: "堪培拉", jyutping: "ham1 pui4 laai1", meaning: "Canberra" },
            { char: "北京", jyutping: "bak1 ging1", meaning: "Beijing" }, { char: "上海", jyutping: "soeng6 hoi2", meaning: "Shanghai" },
            { char: "廣州", jyutping: "gwong2 zau1", meaning: "Guangzhou" }, { char: "香港", jyutping: "hoeng1 gong2", meaning: "Hong Kong" },
            { char: "臺灣", jyutping: "toi4 waan1", meaning: "Taiwan" }, { char: "西安", jyutping: "sai1 on1", meaning: "Xi'an" }
        ],
        "Festivals": [
            { char: "春節", jyutping: "ceon1 zit3", meaning: "Spring Festival" }, { char: "元旦", jyutping: "jyun4 daan3", meaning: "New Year's Day" },
            { char: "中秋節", jyutping: "zung1 cau1 zit3", meaning: "Mid-Autumn Festival" }, { char: "端午節", jyutping: "dyun1 ng5 zit3", meaning: "Dragon Boat Festival" },
            { char: "聖誕節", jyutping: "sing3 daan3 zit3", meaning: "Christmas" }
        ]
    }
};
